### ISSUE TITLE
Randomtools folder is empty in the releases download.

### ISSUE THREAD

**Issue by Oronjoker** [abyssonym/mighty_power#1]
Randomtools folder is empty in the releases download, so the randomizer errors out when opened.

**Comment by abyssonym** [comment]
Thanks for bringing this to my attention. It seems that Github stupidly does not include submodules in releases. The expected solution is probably to force the end user to use `git clone` from the command line to download the submodules. For convenience I've attached an archive of the source code (with the submodule included) to the releases page. https://github.com/abyssonym/mighty_power/releases/download/v1/mighty_power_source_full.zip

(the windows binary should not require the submodule to run)
