### ISSUE TITLE
No exe

### ISSUE THREAD

**Issue by DiosMeow** [abyssonym/mighty_power#3]
"Windows users may use the executable file, "mighty_power.exe"."

The exe file is not present in the download.

**Comment by abyssonym** [comment]
This is a bit different from my previous randomizers, you have to download it from the [releases](https://github.com/abyssonym/mighty_power/releases) page. Make sure to download the file `mighty_power_windows.zip`.

**Comment by DiosMeow** [comment]
Thank you. I would not have found that on my own.
